{
 "title": "VulnerableApp - Monitoreo General",
 "tags": [
  "vulnerableapp",
  "p4h-3"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Eventos por nivel en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"vulnerableapp\"}[$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Panel 1 - Errores (level=\"ERR\")",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\", level=\"ERR\"}"
    }
   ]
  },
  {
   "title": "Panel 2 - Autenticaciones (application=\"Security\")",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\", application=\"Security\"}"
    }
   ]
  },
  {
   "title": "Panel 3 - Auditoria (application=\"Audit\")",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\", application=\"Audit\"}"
    }
   ]
  }
 ]
}